//
// Copyright (c) Brian Hernandez. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.
//

using UnityEngine;


/// <summary>
/// This is a very demo-ey example of how to interpret the input generated by the
/// MouseFlightController. The plane flies towards the MouseAimPos automatically in
/// a similar fashion to how War Thunder's Instructor does it. There are also
/// keyboard overrides for flight control. It's not perfect, but it works well enough
/// for an example.
/// </summary>
[RequireComponent(typeof(Rigidbody))]
public class PlayerShipMovement : MonoBehaviour
{
    [Header("Components")]
    [SerializeField] private PlayerMovementController controller = null;

    [Header("Physics")]
    [Tooltip("Force to push plane forwards with")] public float thrust = 100f;
    [Tooltip("Pitch, Yaw, Roll")] public Vector3 turnTorque = new Vector3(90f, 25f, 45f);
    [Tooltip("Multiplier for all forces")] public float forceMult = 1000f;

    [Header("Autopilot")]
    [Tooltip("Sensitivity for autopilot flight.")] public float sensitivity = 5f;
    [Tooltip("Angle at which airplane banks fully into target.")] public float aggressiveTurnAngle = 10f;

    [Header("Input")]
    [SerializeField][Range(-1f, 1f)] private float pitch = 0f;
    [SerializeField][Range(-1f, 1f)] private float yaw = 0f;
    [SerializeField][Range(-1f, 1f)] private float roll = 0f;

    public float Pitch { set { pitch = Mathf.Clamp(value, -1f, 1f); } get { return pitch; } }
    public float Yaw { set { yaw = Mathf.Clamp(value, -1f, 1f); } get { return yaw; } }
    public float Roll { set { roll = Mathf.Clamp(value, -1f, 1f); } get { return roll; } }

    private Rigidbody rigid;

    private bool rollOverride = false;
    private bool pitchOverride = false;

    private void Awake()
    {
        rigid = GetComponent<Rigidbody>();

        if (controller == null)
            Debug.LogError(name + ": Plane - Missing reference to MouseFlightController!");
    }

    private void Update()
    {
        // When the player commands their own stick input, it should override what the
        // autopilot is trying to do.
        rollOverride = false;
        pitchOverride = false;

        // Read from the new Input System (Gamepad/Keyboard) and fallback to legacy Input if not available.
        float keyboardRoll = 0f;
        float keyboardPitch = 0f;
        var gp = UnityEngine.InputSystem.Gamepad.current;
        var kb = UnityEngine.InputSystem.Keyboard.current;

        if (gp != null)
        {
            keyboardRoll = gp.leftStick.ReadValue().x;
        }
        else if (kb != null)
        {
            keyboardRoll = (kb.dKey.isPressed ? 1f : 0f) + (kb.aKey.isPressed ? -1f : 0f);
        }

        if (Mathf.Abs(keyboardRoll) > .25f)
        {
            rollOverride = true;
        }

        if (gp != null)
        {
            keyboardPitch = gp.leftStick.ReadValue().y;
        }
        else if (kb != null)
        {
            keyboardPitch = (kb.wKey.isPressed ? 1f : 0f) + (kb.sKey.isPressed ? -1f : 0f);
        }

        if (Mathf.Abs(keyboardPitch) > .25f)
        {
            pitchOverride = true;
            rollOverride = true;
        }

        // Calculate the autopilot stick inputs.
        float autoYaw = 0f;
        float autoPitch = 0f;
        float autoRoll = 0f;
        if (controller != null)
            RunAutopilot(controller.MouseAimPos, out autoYaw, out autoPitch, out autoRoll);

        // Use either keyboard or autopilot input.
        yaw = autoYaw;
        pitch = (pitchOverride) ? keyboardPitch : autoPitch;
        roll = (rollOverride) ? keyboardRoll : autoRoll;

        

        // // Simple throttle control.
        // float throttleInput = 0f;
        // if (gp != null)
        // {
        //     throttleInput = gp.rightTrigger.ReadValue() - gp.leftTrigger.ReadValue();
        // }
        // else if (kb != null)
        // {
        //     throttleInput = (kb.leftShiftKey.isPressed ? 1f : 0f) + (kb.leftCtrlKey.isPressed ? -1f : 0f);
        // }

        // thrust += throttleInput * Time.deltaTime * forceMult;
        // // thrust = Mathf.Clamp(thrust, 0f, 500f);

        // // Appply forces without using Rigidbody.
        // transform.position += transform.forward * (thrust * Time.deltaTime);
        // transform.Rotate(new Vector3(turnTorque.x * pitch,
        //                              turnTorque.y * yaw,
        //                              -turnTorque.z * roll) * Time.deltaTime);

    }

    private void RunAutopilot(Vector3 flyTarget, out float yaw, out float pitch, out float roll)
    {
        // This is my usual trick of converting the fly to position to local space.
        // You can derive a lot of information from where the target is relative to self.
        var localFlyTarget = transform.InverseTransformPoint(flyTarget).normalized * sensitivity;
        var angleOffTarget = Vector3.Angle(transform.forward, flyTarget - transform.position);

        // IMPORTANT!
        // These inputs are created proportionally. This means it can be prone to
        // overshooting. The physics in this example are tweaked so that it's not a big
        // issue, but in something with different or more realistic physics this might
        // not be the case. Use of a PID controller for each axis is highly recommended.

        // ====================
        // PITCH AND YAW
        // ====================

        // Yaw/Pitch into the target so as to put it directly in front of the aircraft.
        // A target is directly in front the aircraft if the relative X and Y are both
        // zero. Note this does not handle for the case where the target is directly behind.
        yaw = Mathf.Clamp(localFlyTarget.x, -1f, 1f);
        pitch = -Mathf.Clamp(localFlyTarget.y, -1f, 1f);

        // ====================
        // ROLL
        // ====================

        // Roll is a little special because there are two different roll commands depending
        // on the situation. When the target is off axis, then the plane should roll into it.
        // When the target is directly in front, the plane should fly wings level.

        // An "aggressive roll" is input such that the aircraft rolls into the target so
        // that pitching up (handled above) will put the nose onto the target. This is
        // done by rolling such that the X component of the target's position is zeroed.
        var agressiveRoll = Mathf.Clamp(localFlyTarget.x, -1f, 1f);

        // A "wings level roll" is a roll commands the aircraft to fly wings level.
        // This can be done by zeroing out the Y component of the aircraft's right.
        var wingsLevelRoll = transform.right.y;

        // Blend between auto level and banking into the target.
        var wingsLevelInfluence = Mathf.InverseLerp(0f, aggressiveTurnAngle, angleOffTarget);
        roll = Mathf.Lerp(wingsLevelRoll, agressiveRoll, wingsLevelInfluence);
    }

    private void FixedUpdate()
    {
        // Ultra simple flight where the plane just gets pushed forward and manipulated
        // with torques to turn.
        rigid.AddRelativeForce(Vector3.forward * thrust * forceMult, ForceMode.Force);
        rigid.AddRelativeTorque(new Vector3(turnTorque.x * pitch,
                                            turnTorque.y * yaw,
                                            -turnTorque.z * roll) * forceMult,
                                ForceMode.Force);
    }
}


// using UnityEngine;
// using UnityEngine.InputSystem;


// public class PlayerShipMovement : MonoBehaviour
// {
//     new Rigidbody rigidbody;

//     const float FORCEMULT = 100.0f;

//     public float thrust;
//     public float yaw;
//     public float pitch;

//     void Awake()
//     {
//         rigidbody = GetComponent<Rigidbody>();
//     }

//     // FixedUpdate is called once per physics frame
//     void FixedUpdate()
//     {
//         float inPitch = Keyboard.current.sKey.isPressed ? -1.0f :
//                         Keyboard.current.wKey.isPressed ? 1.0f : 0.0f;
//         float inYaw = Keyboard.current.aKey.isPressed ? -1.0f :
//                       Keyboard.current.dKey.isPressed ? 1.0f : 0.0f;

//         rigidbody.AddRelativeForce(0.0f, 0.0f, thrust * FORCEMULT * Time.deltaTime);

//         rigidbody.AddRelativeTorque(inPitch * pitch * FORCEMULT * Time.deltaTime,
//                                     inYaw * yaw * FORCEMULT * Time.deltaTime,
//                                     -inYaw * yaw * FORCEMULT * 0.5f * Time.deltaTime);
//     }
// }
